import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider, auth } from '@clerk/nextjs'
import { ToastProvider } from '@/providers/toast-provider'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (

    <ClerkProvider> 


      <html lang="en">
        {/* <ToastProvider/> */}
        <body>{children}</body>
      </html>
      
    </ClerkProvider>
  )
}
