import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider, auth } from "@clerk/nextjs";
import { ToastProvider } from "@/providers/toast-provider";
import { Sora } from "next/font/google";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        {/* <ToastProvider/> */}
        <body className={sora.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
